### ISSUE TITLE
link to spec/tool that supports this?

### ISSUE THREAD

**Issue by benmosher** [mathieumg/tempura#2]
This looks cool. I am not familiar with what part of what spec/tool executes these tags, though. Haven't seen this syntax, that I can remember.

Can you add a link/blurb to the README to whatever powers this? I'd like to read more. 😊

**Comment by benmosher** [comment]
a bit of googling yields https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings#Tagged_template_strings . maybe not so tough to find after all. 😳

**Comment by mathieumg** [comment]
Hi!

Thanks for the remark, it's true that anyone not familiar with tagged templates wouldn't know how to use this out of the box. I'll add the MDN link you provided to the readme the second I get a chance. :)

**Comment by mathieumg** [comment]
The package has been deprecated in favor of https://github.com/declandewet/common-tags!
